export const Tags: Record<string, string> = {
    JS: 'js',
    JAVASCRIPT: 'JavaScript',
    ES6: 'es6',
    TS: 'ts',
    TYPESCRIPT: 'typescript',
    REACT: 'react',
    VUE: 'vue',
    SVELTE: 'svelte',
    NODE: 'node',
    NPM: 'npm',
    WEBPACK: 'webpack',
    HTML: 'html',
    HTML5: 'html5',
    CSS: 'css',
    CSS3: 'css3',
    CSSHEETS: 'cascading style sheets',
    SASS: 'sass',
    SCSS: 'scss',
    SALESFORCE: 'salesforce',
    SFCC: 'sfcc',
    FLUTTER: 'flutter',
    DART: 'dart',
    IOS: 'iOS',
    IPHONE: 'iPhone',
    ANDROID: 'android',
    MOBILE: 'mobile',
    SMARTPHONE: 'smartphone',
    REACTNATIVE: 'react native',
    JAVA: 'java',
    JEE: 'jee',
    KOTLIN: 'kotlin',
    JETPACKC: 'jetpack compose'
}

export const TagGroups: Record<string, Array<string>> = {
    JS: [Tags.JS, Tags.JAVASCRIPT, Tags.ES6],
    TS: [Tags.TS, Tags.TYPESCRIPT],
    REACT: [Tags.REACT],
    VUE: [Tags.VUE],
    SVELTE: [Tags.SVELTE],
    NODE: [Tags.NODE, Tags.NPM],
    WEBPACK: [Tags.WEBPACK],
    HTML: [Tags.HTML, Tags.HTML5],
    CSS: [Tags.CSS, Tags.CSS3, Tags.CSSHEETS],
    SASS: [Tags.SASS, Tags.SCSS],
    SFCC: [Tags.SALESFORCE, Tags.SFCC],
    FLUTTER: [Tags.FLUTTER, Tags.DART],
    IOS: [Tags.IOS, Tags.IPHONE],
    ANDROID: [Tags.ANDROID],
    MOBILE: [Tags.MOBILE, Tags.SMARTPHONE],
    REACTNATIVE: [Tags.REACTNATIVE],
    JAVA: [Tags.JAVA, Tags.JEE],
    KOTLIN: [Tags.KOTLIN],
    JETPACKC: [Tags.JETPACKC]
}